posventa/core/urls.py
from django.urls import path, include
from .views import (
    HomeView, 
    ProviderView, ProviderCreateView, ProviderUpdateView, ProviderDeleteView,
    ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView,
    CategoryView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    SaleView, SaleCreateView,
    ClientView, ClientCreateView,
    export_providers, export_products, export_categories
    )
from rest_framework import routers
from .api import ProviderViewSet as PV
from .api import ProductViewSet, SaleViewSet, ClientViewSet

router = routers.SimpleRouter()
router.register(r'providers', PV)
router.register(r'products', ProductViewSet)
router.register(r'sales', SaleViewSet)
router.register(r'clients', ClientViewSet)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # api endpoints
    path('api/v1/', include(router.urls)),

    # providers urls
    path('providers/', ProviderView.as_view(), name='providers'),
    path('providers/new/', ProviderCreateView.as_view(), name='new_providers'),
    path('providers/edit/<int:pk>/', ProviderUpdateView.as_view(), name='provider_edit'),
    path('providers/delete/<int:pk>/', ProviderDeleteView.as_view(), name='provider_delete'),

    # products urls
    path('products/', ProductView.as_view(), name='products'),
    path('products/new', ProductCreateView.as_view(), name='new_products'),
    path('products/edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),


    # categories urls
    path('categories/', CategoryView.as_view(), name='categories'),
    path('categories/new', CategoryCreateView.as_view(), name='new_categories'),
    path('categories/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    # sales urls
    path('sales/', SaleView.as_view(), name='sales'),
    path('sales/new', SaleCreateView.as_view(), name='new_sales'),

    # clients urls
    path('clients/', ClientView.as_view(), name='clients'),
    path('clients/new', ClientCreateView.as_view(), name='new_clients'),

    # all export urls
    path('export_providers/', export_providers, name='export_providers'),
    path('export_products/', export_products, name='export_products'),
    path('export_categories/', export_categories, name='export_categories'),
]

posventa/posventa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('chacho/', admin.site.urls),
    path('accounts/', include('user.urls', namespace="accounts")),
    path('', include('core.urls', namespace="core")),
]
from django.conf.urls.static import static

# for dev static files serving
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posventa/user/urls.py
from .views import LoginView, LogoutView, impersonate, SettingsView
from django.urls import path, include

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('impersonate/', impersonate, name='impersonate'),
    path('settings/', SettingsView.as_view(), name='settings')
]

posventa/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{title|default:"posventa"}}</title>
    {% block css %}
      <!-- Tell the browser to be responsive to screen width -->
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <!-- Bootstrap 3.3.7 -->
      <link rel="stylesheet" href="{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="{% static "bower_components/font-awesome/css/font-awesome.min.css" %}">
      <!-- Ionicons -->
      <link rel="stylesheet" href="{% static "bower_components/Ionicons/css/ionicons.min.css" %}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
      <!-- AdminLTE Skins. Choose a skin from the css/skins
          folder instead of downloading all of them to reduce the load. -->
      <link rel="stylesheet" href="{% static "dist/css/skins/_all-skins.min.css" %}">
      <!-- Morris chart -->
      <link rel="stylesheet" href="{% static "bower_components/morris.js/morris.css" %}">
      <!-- jvectormap -->
      <link rel="stylesheet" href="{% static "bower_components/jvectormap/jquery-jvectormap.css" %}">
      <!-- Date Picker -->
      <link rel="stylesheet" href="{% static "bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" %}">
      <!-- Daterange picker -->
      <link rel="stylesheet" href="{% static "bower_components/bootstrap-daterangepicker/daterangepicker.css" %}">
      <link rel="stylesheet" href="{% static "plugins/fontawesome/fontawesome-all.css" %}">
      <!-- bootstrap wysihtml5 - text editor -->
      <link rel="stylesheet" type="text/css" href="{% static "css/datatables.min.css" %}" />
      <link rel="stylesheet" type="text/css" href="{% static "plugins/DataTables/css/jquery.dataTables.min.css"  %}" />
      <link rel="stylesheet" type="text/css" href="{% static "plugins/select2/vendor/select2/select2.min.css"  %}" />      
      <link rel="stylesheet" href="{% static "plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    {% endblock css %}
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
      <!-- Navigation -->
    <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">
            <b>Ps</b>V</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">
            <b>Pos</b>venta</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->
                  <span class="hidden-xs">{{ store }}</span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url "accounts:settings" %}">Configuraciones</a>
                  </li>
                  <li>
                    <a href="{% url "accounts:logout" %}">Salir</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{% if nbar == 'home' %}active treeview{% endif %}">
              <a href="{% url "core:home" %}">
                <i class="fa ion-arrow-graph-up-right"></i>
                <span>Dashboard</span>
              </a>
            </li>
            <li class="{% if nbar == 'categories' %}active treeview{% endif %}">
              <a href="{% url "core:categories" %}">
                <i class="fa fa-bars"></i>
                <span>Categorias</span>
              </a>
            </li>
            <li class="{% if nbar == 'products' %}active treeview{% endif %}">
              <a href="{% url "core:products" %}">
                <i class="fa fa-box"></i>
                <span>Productos</span>
              </a>
            </li>
            <li class="{% if nbar == 'providers' %}active treeview{% endif %}">
              <a href="{% url "core:providers" %}">
                <i class="fa fa-truck"></i>
                <span>Proveedores</span>
              </a>
            </li>
            <li class="{% if nbar == 'sales' %}active treeview{% endif %}">
              <a href="{% url "core:sales" %}">
                <i class="fa fa-shopping-cart"></i>
                <span>Ventas</span>
              </a>
            </li>
            <li class="{% if nbar == 'clients' %}active treeview{% endif %}">
              <a href="{% url "core:clients" %}">
                <i class="fa fa-users"></i>
                <span>Clientes</span>
              </a>
            </li>
            <li class="{% if nbar == 'inventaries' %}active treeview{% endif %}">
              <a href="#">
                <i class="fa fa-clipboard-list"></i>
                <span>Inventario</span>
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>
        <!-- Content Wrapper. Contains page content -->
        <!-- Content Header (Page header) -->
        <div class="content-wrapper">
         {% block content %}
          <!-- Main content -->
          <section class="content">
          </section>
         {% endblock content %}
        <!-- /.content -->
      </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Posventa Version</b> 1.0.0
      </div>
      <strong>Copyright &copy; 2019.</strong> All rightsreserved.
    </footer>
      <!-- Footer -->
      <!-- Bootstrap core JavaScript -->
      </div>
      <!-- jQuery 3 -->
      <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
      <!-- jQuery UI 1.11.4 -->
      <script src="{% static "bower_components/jquery-ui/jquery-ui.min.js" %}"></script>
      <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
      <script>
        $.widget.bridge('uibutton', $.ui.button);
      </script>
      <!-- Bootstrap 3.3.7 -->
      <script src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
      <!-- Morris.js charts -->
      <script src="{% static "bower_components/raphael/raphael.min.js" %}"></script>
      <script src="{% static "bower_components/morris.js/morris.min.js" %}"></script>
      <!-- Sparkline -->
      <script src="{% static "bower_components/jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
      <!-- jvectormap -->
      <script src="{% static "plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}"></script>
      <script src="{% static "plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}"></script>
      <!-- jQuery Knob Chart -->
      <script src="{% static "bower_components/jquery-knob/dist/jquery.knob.min.js" %}"></script>
      <!-- daterangepicker -->
      <script src="{% static "bower_components/moment/min/moment.min.js" %}"></script>
      <script src="{% static "bower_components/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
      <!-- datepicker -->
      <script src="{% static "bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" %}"></script>
      <!-- Bootstrap WYSIHTML5 -->
      <script src="{% static "plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}"></script>
      <!-- Slimscroll -->
      <script src="{% static "bower_components/jquery-slimscroll/jquery.slimscroll.min.js" %}"></script>
      <!-- FastClick -->
      <script src="{% static "bower_components/fastclick/lib/fastclick.js" %}"></script>
      <!-- AdminLTE App -->
      <script src="{% static "dist/js/adminlte.min.js" %}"></script>
      <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
      <script src="{% static "dist/js/pages/dashboard.js" %}"></script>
      <!-- AdminLTE for demo purposes -->
      <script src="{% static "dist/js/demo.js" %}"></script>
      <script type="text/javascript" src="{% static "js/datatables.min.js" %}"></script>
      <script src="{% static "plugins/DataTables/js/jquery.dataTables.min.js" %}"></script>
      <script src="{% static "plugins/select2/vendor/select2/select2.min.js" %}"></script>
      
      {% block extra_js%}{% endblock %}
  </body>

</html>