posventa/core/urls.py
from django.urls import path, include
from .views import (
    HomeView, 
    ProviderView, ProviderCreateView, ProviderUpdateView, ProviderDeleteView,
    ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView,
    CategoryView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    SaleView, SaleCreateView,
    ClientView, ClientCreateView,
    export_providers, export_products, export_categories
    )
from rest_framework import routers
from .api import ProviderViewSet as PV
from .api import ProductViewSet, SaleViewSet, ClientViewSet

router = routers.SimpleRouter()
router.register(r'providers', PV)
router.register(r'products', ProductViewSet)
router.register(r'sales', SaleViewSet)
router.register(r'clients', ClientViewSet)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # api endpoints
    path('api/v1/', include(router.urls)),

    # providers urls
    path('providers/', ProviderView.as_view(), name='providers'),
    path('providers/new/', ProviderCreateView.as_view(), name='new_providers'),
    path('providers/edit/<int:pk>/', ProviderUpdateView.as_view(), name='provider_edit'),
    path('providers/delete/<int:pk>/', ProviderDeleteView.as_view(), name='provider_delete'),

    # products urls
    path('products/', ProductView.as_view(), name='products'),
    path('products/new', ProductCreateView.as_view(), name='new_products'),
    path('products/edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),


    # categories urls
    path('categories/', CategoryView.as_view(), name='categories'),
    path('categories/new', CategoryCreateView.as_view(), name='new_categories'),
    path('categories/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    # sales urls
    path('sales/', SaleView.as_view(), name='sales'),
    path('sales/new', SaleCreateView.as_view(), name='new_sales'),

    # clients urls
    path('clients/', ClientView.as_view(), name='clients'),
    path('clients/new', ClientCreateView.as_view(), name='new_clients'),

    # all export urls
    path('export_providers/', export_providers, name='export_providers'),
    path('export_products/', export_products, name='export_products'),
    path('export_categories/', export_categories, name='export_categories'),
]

posventa/posventa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('chacho/', admin.site.urls),
    path('accounts/', include('user.urls', namespace="accounts")),
    path('', include('core.urls', namespace="core")),
]
from django.conf.urls.static import static

# for dev static files serving
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posventa/core/views.py
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from .models import Store, Provider, Product, Category, Sale, Client
from .forms import ProviderForm, ProductForm, CategoryForm, SaleProductForm, ClientForm
from django.utils.translation import ugettext as _
from .utils import export_to_csv
from django.contrib.auth.decorators import login_required

class HomeView(LoginRequiredMixin, TemplateView):
	template_name = 'core/index.html'


class ProviderView(LoginRequiredMixin, TemplateView):
	template_name = 'core/providers.html'

	def get_context_data(self, **kwargs):
		context = super(ProviderView, self).get_context_data(**kwargs)
		store = Store.objects.get(user__id=self.request.user.id)
		context['providers'] = Provider.objects.filter(
			store__id=store.id).order_by('id')
		return context

class ProviderCreateView(LoginRequiredMixin, CreateView):
	form_class = ProviderForm
	template_name = 'core/provider_new.html'
	success_url = '/providers/'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		store = Store.objects.get(user__id=self.request.user.id)
		self.object.store = store
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Agregar'
		context['breadcrumb'] = 'Nuevo'
		return context


class ProviderUpdateView(LoginRequiredMixin, UpdateView):
	model = Provider
	form_class = ProviderForm
	success_url = '/providers/'
	template_name_suffix = '_new'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Actualizar'
		context['breadcrumb'] = 'Actualizar'
		return context


class ProviderDeleteView(LoginRequiredMixin, DeleteView):
	model = Provider
	success_url = '/providers/'

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()
		return HttpResponseRedirect(self.get_success_url())


class ProductView(LoginRequiredMixin, TemplateView):
	template_name = 'core/products.html'
	def get_context_data(self, **kwargs):
		context = super(ProductView, self).get_context_data(**kwargs)
		context['products'] = Product.objects.filter(
			store__id=self.request.user.get_store.id).order_by('id')
		return context


class ProductCreateView(LoginRequiredMixin, CreateView):
	form_class = ProductForm
	template_name = 'core/product_new.html'
	success_url = '/products/'

	def get_form_kwargs(self):
		kwargs = super(ProductCreateView, self).get_form_kwargs()
		kwargs['request'] = self.request
		return kwargs

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.store = self.request.user.get_store
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Agregar'
		context['breadcrumb'] = 'Nuevo'
		return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
	model = Product
	form_class = ProductForm
	success_url = '/products/'
	template_name_suffix = '_new'

	def get_form_kwargs(self):
		kwargs = super(ProductUpdateView, self).get_form_kwargs()
		kwargs['request'] = self.request
		return kwargs

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.store = self.request.user.get_store
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Actualizar'
		context['breadcrumb'] = 'Actualizar'
		return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	model = Product
	success_url = '/products/'

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()
		return HttpResponseRedirect(self.get_success_url())


class CategoryView(LoginRequiredMixin, TemplateView):
	template_name = 'core/categories.html'

	def get_context_data(self, **kwargs):
		context = super(CategoryView, self).get_context_data(**kwargs)
		context['categories'] = Category.objects.filter(
			store__id=self.request.user.get_store.id).order_by('id')
		return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
	form_class = CategoryForm
	template_name = 'core/category_new.html'
	success_url = '/categories/'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.store = self.request.user.get_store
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Agregar'
		context['breadcrumb'] = 'Nuevo'
		return context


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
	model = Category
	form_class = CategoryForm
	success_url = '/categories/'
	template_name_suffix = '_new'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Actualizar'
		context['breadcrumb'] = 'Actualizar'
		return context


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
	model = Category
	success_url = '/categories/'

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()
		return HttpResponseRedirect(self.get_success_url())


class SaleView(LoginRequiredMixin, TemplateView):
	template_name = 'core/sales.html'
	
	def get_context_data(self, **kwargs):
		context = super(SaleView, self).get_context_data(**kwargs)
		context['sales'] = Sale.objects.filter(
			store__id=self.request.user.get_store.id).order_by('id')
		return context


class SaleCreateView(LoginRequiredMixin, TemplateView):
	template_name = 'core/sale_new_react.html'

	def get_context_data(self, **kwargs):
		context = super(SaleCreateView, self).get_context_data(**kwargs)
		context['store_id'] = self.request.user.get_store.id
		return context


class ClientView(LoginRequiredMixin, TemplateView):
	template_name = 'core/clients.html'

	def get_context_data(self, **kwargs):
		context = super(ClientView, self).get_context_data(**kwargs)
		context['clients'] = Client.objects.filter(
			store__id=self.request.user.get_store.id).order_by('id')
		return context


class ClientCreateView(LoginRequiredMixin, CreateView):
	form_class = ClientForm
	template_name = 'core/client_new.html'
	success_url = '/clients/'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.store = self.request.user.get_store
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Agregar'
		context['breadcrumb'] = 'Nuevo'
		return context

@login_required
def export_providers(request):
	user = request.user
	try:
		providers = Provider.objects.filter(store_id=user.get_store.id)
	except Exception:
		raise
	else:
		heads = [
			[
				_(u'Nombre'),
				_(u'Apellido'),
				_(u'Nombre comercial'),
				_(u'DNI'),
				_(u'CUIT'),
				_(u'Teléfono'),
				_(u'Email'),
				_(u'Direccion'),
			]
		]
		data = ([
			ob.first_name.title(),
			ob.last_name.title(),
			ob.business_name,
			ob.dni,
			ob.cuit,
			ob.phone,
			ob.email,
			ob.address
		] for ob in providers)
		return export_to_csv(user.id, heads, data)


@login_required
def export_products(request):
	user = request.user
	try:
		products = Product.objects.filter(store_id=user.get_store.id)
	except Exception:
		raise
	else:
		heads = [
			[
				_(u'Codigo'),
				_(u'Nombre'),
				_(u'Proveedor'),
				_(u'Categoria'),
				_(u'Cantidad'),
				_(u'Precio de costo'),
				_(u'Precio de venta')
			]
		]
		data = ([
				ob.code,
				ob.name,
				ob.provider.business_name,
				ob.category,
                '%d' % ob.unity,
                '%.2f' % ob.cost_price,
                '%.2f' % ob.sale_price,

		] for ob in products)
		return export_to_csv(user.id, heads, data)


@login_required
def export_categories(request):
	user = request.user
	try:
		categories = Category.objects.filter(store_id=user.get_store.id)
	except Exception:
		raise
	else:
		heads = [
			[
				_(u'Codigo'),
				_(u'Nombre')
			]
		]
		data = ([
			ob.id,
			ob.name,
		] for ob in categories)
		return export_to_csv(user.id, heads, data)

posventa/templates/core/categories.html
{% extends "base.html" %} {% block content %}
<section class="content-header">
    <h1>
        Categorias
        <small>Panel de Control</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{% url "core:home" %}">
                <i class="fa fa-home"></i> Home
            </a>
        </li>
        <li class="active">Categorias</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Page Content -->
    <div class="box">
        <div class="box-header" style="margin-top: 10px; margin-bottom: -20px">
            <div class="col-md-12">
                <div class="col-md-5">
                    <h3 class="box-title">Categorias</h3>
                </div>
                <div class="col-md-7" style="text-align: right;">
                    <a href="{% url "core:new_categories" %}" style="color: white; text-decoration: none !important;">
                        <button type="button" class="btn btn-success btn-sm">
                            <i class="fas fa-plus"></i>
                            <span>Nuevo</span>
                        </button>
                    </a>
                    <a href="#" style="color: white; text-decoration: none !important;">
                        <button type="button" class="btn btn-success btn-sm">
                            <i class="fas fa-upload"></i>
                            <span>Importar</span>
                        </button>
                    </a>
                    <a href="{% url "core:export_categories" %}" style="color: white; text-decoration: none !important;">
                        <button type="button" class="btn btn-success btn-sm">
                            <i class="fas fa-download"></i>
                            <span>Exportar</span>
                        </button>
                    </a>
                </div>
            </div>
        </div>
        <hr>
        <div class="box-body no-padding">
            <div class="col-md-12">
                <table id="table-categories" class="display compact table-striped table-categories" style="width:100%">
                    <thead>
                        <th style="width: 10px">#</th>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </thead>
                    {% for category in categories %}
                    <tr id=forloop.counter>
                        <td>{{category.id}}</td>
                        <td>{{category.name}}</td>
                        <td>
                            <center>
                                <a href="{{category.get_delete_absolute_url}}">
                                    <button type="button" class="btn btn-xs btn-danger">
                                        <i class="ion-android-delete"></i>
                                    </button>
                                </a>
                                <a href="{{category.get_edit_absolute_url}}">
                                    <button type="button" class="btn btn-xs btn-warning">
                                        <i class="ion-edit"></i>
                                    </button>
                                </a>
                            </center>
                        </td>
                    </tr>
                    {% endfor %}
                    <thead>
                        <th style="width: 10px">#</th>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</section>
<!-- /.container -->
{% endblock content%} {% block extra_js %}
<script type="text/javascript" language="javascript" class="init">
    $(function () {
        $('#table-categories').dataTable({
            "ordering": true,
            "bJQueryUI": true,
            "bSort": false,
            "bPaginate": true,
            "sPaginationType": "full_numbers",
            "iDisplayLength": 10,
            "language": {
                "paginate": {
                    "previous": "Anterior",
                    "next": "Siguiente",
                    "first": "Primera",
                    "last": "Ultima",
                },
                "info": "Mostrando _START_ de _END_ de _TOTAL_ registros",
                "infoEmpty": "No hay informacion para mostrar",
                "processing": "Procesando...",
                "search": "Buscar:",
                "lengthMenu": "Mostrar _MENU_ registros",
            },
            "columns": [
                { "orderDataType": "dom-text-numeric" },
                { "orderDataType": "dom-text-numeric" },
                { "orderDataType": "dom-text-numeric" }
            ]
        });
    });
</script>
{% endblock %}

posventa/templates/core/category_confirm_delete.html
{% extends "base.html" %} {% block content %}
<section class="content-header">
    <h1>
        Categorias
        <small>Panel de Control</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{% url "core:home" %}">
                <i class="fa fa-home"></i> Home
            </a>
        </li>
        <li class="active">Categorias</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Page Content -->
    <div class="box">
        <div class="box-header" style="margin-top: 10px; margin-bottom: -20px">
            <div class="col-md-12">
                <div class="col-md-5">
                    <h3 class="box-title">Categorias</h3>
                </div>
            </div>
        </div>
        <hr>
        <div class="box-body no-padding">
            <div class="col-md-12">
                <center>
                    <h2>Eliminar Categoria</h2>
                    <form method="post">{% csrf_token %}
                        <p>Estas seguro de eliminar la categoria "{{ object }}"?</p>
                        <input type="submit" value="Confirmar" class="btn btn-labeled btn-success" />
                        <a href="{% url 'core:categories' %}">No,cancelar.</a>
                    </form>
                </center>
                <br>
            </div>
        </div>
    </div>
</section>
<!-- /.container -->
{% endblock content%}

posventa/templates/core/category_new.html
{% extends "base.html" %} {% block content %}
<section class="content-header">
    <h1>
        Categorias
        <small>Panel de Control</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{% url "core:home" %}">
                <i class="fa fa-home"></i> Home
            </a>
        </li>
        <li>
            <a href=" {% url "core:categories" %} ">
                <i class="fa fa-bars"></i> Categorias
            </a>
        </li>
        <li class="active">{{breadcrumb}}</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Page Content -->
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        {% if title == 'Agregar' %}
                            {{title}} Nueva Categoria
                        {% else %}
                            {{title}} Categoria
                        {% endif %}
                    </h3>
                </div>
                <form role="form" method="POST">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            {{ form.name }} {{ form.name.errors }}
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="button" class="btn btn-danger">
                            <a href="{% url "core:categories" %}" style="color: white; text-decoration: none !important;">
                                Cancelar
                            </a>
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- /.container -->
{% endblock content%}

posventa/templates/core/client_new.html
{% extends "base.html" %} {% block content %}
<section class="content-header">
    <h1>
        Cliente
        <small>Panel de Control</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{% url "core:home" %}">
                <i class="fa fa-home"></i> Home
            </a>
        </li>
        <li>
            <a href=" {% url "core:providers" %} ">
                <i class="fa fa-users"></i> Cliente
            </a>
        </li>
        <li class="active">{{breadcrumb}}</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Page Content -->
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    {% if title == 'Agregar' %} {{title}} Nuevo Cliente {% else %} {{title}} Proveedor {% endif %}
                </div>
                <form role="form" method="POST">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="business_name">Nombre comercial</label>
                            {{ form.business_name }} {{ form.business_name.errors }}
                        </div>
                        <div class="form-group">
                            <label for="first_name">Nombre</label>
                            {{ form.first_name }} {{ form.first_name.errors }}
                        </div>
                        <div class="form-group">
                            <label for="last_name">Apellido</label>
                            {{ form.last_name }} {{ form.last_name.errors }}
                        </div>
                        <div class="form-group">
                            <label for="dni">DNI</label>
                            {{ form.dni }} {{ form.dni.errors }}
                        </div>
                        <div class="form-group">
                            <label for="dni">CUIT</label>
                            {{ form.cuit }} {{ form.cuit.errors }}
                        </div>
                        <div class="form-group">
                            <label for="phone">Telefono</label>
                            {{ form.phone }} {{ form.phone.errors }}
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            {{ form.email }} {{ form.email.errors }}
                        </div>
                        <div class="form-group">
                            <label for="address">Direccion</label>
                            {{ form.address }} {{ form.address.errors }}
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="button" class="btn btn-danger">
                            <a href="{% url "core:clients" %}" style="color: white; text-decoration: none !important;">
                                Cancelar
                            </a>
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- /.container -->
{% endblock content%}

posventa/templates/core/providers.html
{% extends "base.html" %}
{% block content %}
    <section class="content-header">
        <h1>
            Proveedores
            <small>Panel de Control</small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{% url "core:home" %}">
                    <i class="fa fa-home"></i> Home
                </a>
            </li>
            <li class="active">Proveedores</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Page Content -->   
        <div class="box">
            <div class="box-header" style="margin-top: 10px; margin-bottom: -20px">
                <div class="col-md-12">
                    <div class="col-md-5">
                        <h3 class="box-title">Proveedores</h3>
                    </div>
                    <div class="col-md-7" style="text-align: right;">
                        <a href="{% url "core:new_providers" %}" style="color: white; text-decoration: none !important;">
                            <button type="button" class="btn btn-success btn-sm">
                                <i class="fas fa-plus"></i>
                                <span>Nuevo</span>
                            </button>
                        </a>
                        <a href="#" style="color: white; text-decoration: none !important;">
                            <button type="button" class="btn btn-success btn-sm">
                                <i class="fas fa-upload"></i>
                                <span>Importar</span>
                            </button>
                        </a>
                        <a href="{% url "core:export_providers" %}" style="color: white; text-decoration: none !important;">
                            <button type="button" class="btn btn-success btn-sm">
                                <i class="fas fa-download"></i>
                                <span>Exportar</span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <hr>
            <div class="box-body no-padding">
                <div class="col-md-12">
                    <table id="table-providers" class="display compact table-striped table-providers" style="width:100%">
                        <thead>
                            <th style="width: 10px">#</th>
                            <th>Nombre comercial</th>
                            <th>Telefono</th>
                            <th>CUIT</th>                            
                            <th>Email</th>
                            <th>Direccion</th>
                            <th>Acciones</th>    
                        </thead>
                        {% for provider in providers %} 
                            <tr id=forloop.counter>
                                <td>{{provider.id}}</td>
                                <td>{{provider.business_name}}</td>
                                <td>{{provider.phone}}</td>
                                <td>{{provider.cuit}}</td>                                
                                <td>{{provider.email}}</td>
                                <td>{{provider.address}}</td>
                                <td>
                                    <center>
                                        <a href="{{provider.get_delete_absolute_url}}">
                                            <button type="button" class="btn btn-xs btn-danger">
                                                <i class="ion-android-delete"></i>
                                            </button>
                                        </a>
                                        <a href="{{provider.get_edit_absolute_url}}">
                                            <button type="button" class="btn btn-xs btn-warning">
                                                <i class="ion-edit"></i>
                                            </button>
                                        </a>
                                    </center>
                                </td>
                            </tr>
                        {% endfor %}
                        <thead>
                            <th style="width: 10px">#</th>
                            <th>Nombre comercial</th>
                            <th>Telefono</th>
                            <th>CUIT</th>                            
                            <th>Email</th>
                            <th>Direccion</th>
                            <th>Acciones</th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>      
    </section>
    <!-- /.container -->
{% endblock content%}
{% block extra_js %}
    <script type="text/javascript" language="javascript" class="init">
        $(function () {
            $('#table-providers').dataTable({
                "ordering": true,
                "bJQueryUI": true,
                "bSort": false,
                "bPaginate": true,
                "sPaginationType": "full_numbers",
                "iDisplayLength": 10,
                "language": {
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente",
                        "first": "Primera",
                        "last": "Ultima",
                    },
                    "info": "Mostrando _START_ de _END_ de _TOTAL_ registros",
                    "infoEmpty": "No hay informacion para mostrar",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "lengthMenu": "Mostrar _MENU_ registros",
                },
                "columns": [
                    { "orderDataType": "dom-text-numeric" },
                    { "orderDataType": "dom-text-numeric" },
                    { "orderDataType": "dom-text-numeric" },
                    { "orderDataType": "dom-text-numeric" },
                    { "orderDataType": "dom-text-numeric" },
                    { "orderDataType": "dom-text-numeric" },                    
                    { "orderDataType": "dom-text-numeric" }
                ]
            });
        });
    </script>
    <script>
        function formatFloat(n) {
            var oneDecimal = /\d*\.\d{1}$/;
            var moreThanTwoDecimals = /\d*\.\d{3,}/;
            var twoDecimals = /\d*\.\d{2}/;
            var value = "";
            if (oneDecimal.test(n)) {
                value = n + "0";
                var intPart = value.substr(0, value.length - 3);
                decimalPart = value.substr(value.length - 2);
                intPart = addThousandsSeparator(intPart);
                return intPart + '<sup>' + decimalPart + '</sup>';
            } else if (moreThanTwoDecimals.test(n)) {
                value = parseFloat(n).toFixed(2);
                var intPart = value.substr(0, value.length - 3);
                decimalPart = value.substr(value.length - 2);
                intPart = addThousandsSeparator(intPart);
                return intPart + '<sup>' + decimalPart + '</sup>';
            } else if (twoDecimals.test(n)) {
                value = n.toString();
                var intPart = value.substr(0, value.length - 3);
                decimalPart = value.substr(value.length - 2);
                intPart = addThousandsSeparator(intPart);
                return intPart + '<sup>' + decimalPart + '</sup>';
            }
            return addThousandsSeparator(n.toString());
        }

    </script> 
{% endblock %}